name: Mirror to GitLab
on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Set up Git
        run: |
          git config --global user.name "paniash"
          git config --global user.email "public@ashishpanigrahi.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://paniash:${{ secrets.GITLAB_TOKEN }}@gitlab.com/paniash/mirror.git

      - name: Push to GitLab
        run: |
          git push gitlab main
          git push --tags gitlab
